FROM schoolofdevops/carts-maven AS build
WORKDIR /opt/carts
COPY . .
RUN mvn package

FROM schoolofdevops/carts-maven AS run
COPY --from=build /opt/carts/target/carts.jar /run/carts.jar
WORKDIR /run
EXPOSE 80
CMD java -jar carts.jar --port=80
